version: '3.8'
services:
  db:
    image: mysql:8.0
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  backend:
    build:
      context: "https://github.com/halijtor/spring-backend.git#main:spring-backend"
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:${MYSQL_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    networks:
      - webnet

  frontend:
    build:
      context: "https://github.com/halijtor/react-frontend.git#main:react-frontend"
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    depends_on:
      - backend
    networks:
      - webnet

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

volumes:
  nginx_cache:
  db_data:

networks:
  webnet:
    driver: bridge

